name: TestCase Coverage Check - Comment
on:
  workflow_run:
    workflows: ["TestCase Coverage Check - Build"]
    types: [completed]
permissions:
  contents: read
  pull-requests: write
  actions: read
jobs:
  comment:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.pull_requests[0]
    steps:
      - name: Download JaCoCo Report
        uses: actions/download-artifact@v4
        with:
          name: jacoco-report-${{ github.event.workflow_run.pull_requests[0].number }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          
      - name: Compare JaCoCo Coverage
        uses: madrapps/jacoco-report@v1.7.2
        with:
          paths: jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 0
          title: Code Coverage Report
          comment-type: pr_comment